
AWSTemplateFormatVersion: "2010-09-09"
Resources:

#raw Tweets Database (outputs from the Twitter scraper)
  rawTweetsDatabase:
    Type: AWS::DynamoDB::Table
    Properties:

#requires update
      AttributeDefinitions:
        -
          AttributeName: "Album"
          AttributeType: "S"
        -
          AttributeName: "Artist"
          AttributeType: "S"
        -
          AttributeName: "Sales"
          AttributeType: "N"
        -
          AttributeName: "NumberOfSongs"
          AttributeType: "N"

#requires update
      KeySchema:
        -
          AttributeName: "Album"
          KeyType: "HASH"
        -
          AttributeName: "Artist"
          KeyType: "RANGE"


      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "rawTweetsDatabase"

      GlobalSecondaryIndexes:
        -
          IndexName: "myGSI"
          KeySchema:
            -
              AttributeName: "Sales"
              KeyType: "HASH"
            -
              AttributeName: "Artist"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "NumberOfSongs"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        -
          IndexName: "myGSI2"
          KeySchema:
            -
              AttributeName: "NumberOfSongs"
              KeyType: "HASH"
            -
              AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "Artist"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      LocalSecondaryIndexes:
        -
          IndexName: "myLSI"
          KeySchema:
            -
              AttributeName: "Album"
              KeyType: "HASH"
            -
              AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Artist"
              - "NumberOfSongs"
            ProjectionType: "INCLUDE"

#Processed Tweets Database
  processedTweetsDatabase:
    Type: AWS::DynamoDB::Table
    Properties:

#requires update
      AttributeDefinitions:
        -
          AttributeName: "Album"
          AttributeType: "S"
        -
          AttributeName: "Artist"
          AttributeType: "S"
        -
          AttributeName: "Sales"
          AttributeType: "N"
        -
          AttributeName: "NumberOfSongs"
          AttributeType: "N"

#requires update
      KeySchema:
        -
          AttributeName: "Album"
          KeyType: "HASH"
        -
          AttributeName: "Artist"
          KeyType: "RANGE"


      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "processedTweetsDatabase"

      GlobalSecondaryIndexes:
        -
          IndexName: "myGSI"
          KeySchema:
            -
              AttributeName: "Sales"
              KeyType: "HASH"
            -
              AttributeName: "Artist"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "NumberOfSongs"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        -
          IndexName: "myGSI2"
          KeySchema:
            -
              AttributeName: "NumberOfSongs"
              KeyType: "HASH"
            -
              AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "Artist"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      LocalSecondaryIndexes:
        -
          IndexName: "myLSI"
          KeySchema:
            -
              AttributeName: "Album"
              KeyType: "HASH"
            -
              AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Artist"
              - "NumberOfSongs"
            ProjectionType: "INCLUDE"
