AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Sample Template DynamoDB_Table: This template demonstrates
  the creation of a DynamoDB table.  **WARNING** This template creates an Amazon DynamoDB
  table. You will be billed for the AWS resources used if you create a stack from
  this template.'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC that allows instances access to the Internet.
  SubnetId:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select at two subnets in your selected VPC.
  AZs:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: Select AZs
  OneTimeInstalls:
    Description: On Initial installs, we install the DynamoDB tables and the Elastic Beanstalk
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  HashKeyElementName:
    Description: HashType PrimaryKey Name
    Type: String
    Default: 'id'
    AllowedPattern: '[a-zA-Z0-9]*'
    MinLength: '1'
    MaxLength: '2048'
    ConstraintDescription: must contain only alphanumberic characters
  HashKeyElementType:
    Description: HashType PrimaryKey Type
    Type: String
    Default: S
    AllowedPattern: '[S|N]'
    MinLength: '1'
    MaxLength: '1'
    ConstraintDescription: must be either S or N
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '10'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000

Conditions:
  IsOneTimeInstalls: !Equals [!Ref OneTimeInstalls, 'true']

Resources:
  rawTweetsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Condition: IsOneTimeInstalls
    Properties:
      TableName: raw_tweets
      AttributeDefinitions:
      - AttributeName: !Ref 'HashKeyElementName'
        AttributeType: N
      KeySchema:
      - AttributeName: !Ref 'HashKeyElementName'
        KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: time_tl
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'ReadCapacityUnits'
        WriteCapacityUnits: !Ref 'WriteCapacityUnits'

  processedTweetsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Condition: IsOneTimeInstalls
    Properties:
      TableName: tweet_metrics
      AttributeDefinitions:
      - AttributeName: !Ref 'HashKeyElementName'
        AttributeType: S
      KeySchema:
      - AttributeName: !Ref 'HashKeyElementName'
        KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: time_tl
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'ReadCapacityUnits'
        WriteCapacityUnits: !Ref 'WriteCapacityUnits'

Outputs:
  TableNameRaw:
    Condition: IsOneTimeInstalls
    Value: !Ref 'rawTweetsDynamoDBTable'
    Description: DynamoDB table for raw tweets streaming from twitter_scraper

  TableNameProcessed:
    Condition: IsOneTimeInstalls
    Value: !Ref 'processedTweetsDynamoDBTable'
    Description: DynamoDB table of tweet metrics to support Web App
