AWSTemplateFormatVersion: 2010-09-09
Description: This is the root template that references all other nested templates
Outputs:
  PrivateSecurityGroup:
    Value:
      Fn::Sub: ${VPC.Outputs.PrivateSecurityGroup}
  PrivateSubnetId:
    Value:
      Fn::Sub: ${VPC.Outputs.PrivateSubnetId}
  PublicSecurityGroup:
    Value:
      Fn::Sub: ${VPC.Outputs.PublicSecurityGroup}
  PublicSubnetId:
    Value:
      Fn::Sub: ${VPC.Outputs.PublicSubnetId}
  StackRef:
    Value:
      Ref: VPC
  VPCId:
    Value:
      Fn::Sub: ${VPC.Outputs.VpcId}
Resources:
  ECS:
    Properties:
      Parameters:
        AZs:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateAZs
        SubnetId:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateSubnetId
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/58254b7c2dbfc35f4ae5cdf082101832.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
  PublicBastionHost:
    Properties:
      Parameters:
        AZs:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateAZs
        SubnetId:
          Fn::GetAtt:
          - VPC
          - Outputs.PublicSubnetId
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/37e384d7df2e8410c0ceb0c6188ce97f.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
  VPC:
    Properties:
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/e280814f6501343cb257795f466ff225.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
