AWSTemplateFormatVersion: 2010-09-09
Conditions:
  IsOneTimeInstalls:
    Fn::Equals:
    - Ref: OneTimeInstalls
    - 'true'
Description: This is the root template that references all other nested templates
Outputs:
  PrivateSecurityGroup:
    Value:
      Fn::Sub: ${VPC.Outputs.PrivateSecurityGroup}
  PrivateSubnetId:
    Value:
      Fn::Sub: ${VPC.Outputs.PrivateSubnetId}
  PublicSecurityGroup:
    Value:
      Fn::Sub: ${VPC.Outputs.PublicSecurityGroup}
  PublicSubnetId:
    Value:
      Fn::Sub: ${VPC.Outputs.PublicSubnetId}
  StackRef:
    Value:
      Ref: VPC
  VPCId:
    Value:
      Fn::Sub: ${VPC.Outputs.VpcId}
Parameters:
  OneTimeInstalls:
    AllowedValues:
    - true
    - false
    Default: false
    Description: On Initial installs, we install the DynamoDB tables and the Elastic
      Beanstalk
    Type: String
  SecretsManagerKey:
    Description: Parameter key for ECS instance to talk to Twitter
    MaxLength: '2048'
    MinLength: '1'
    Type: String
Resources:
  DynamoDB:
    Condition: IsOneTimeInstalls
    DependsOn: VPC
    Properties:
      Parameters:
        AZs:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateAZs
        HashKeyElementName: rawTweetsDynamoDBTable
        HashKeyElementType: S
        OneTimeInstalls:
          Ref: OneTimeInstalls
        SubnetId:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateSubnetId
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/f1179076da2885b7affe0f8b8a012db4.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
  ECS:
    Properties:
      Parameters:
        AZs:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateAZs
        SecretsManagerKey:
          Ref: SecretsManagerKey
        SubnetId:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateSubnetId
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/3f70f534966e83510bc17f2875467015.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
  PublicBastionHost:
    DependsOn: VPC
    Properties:
      Parameters:
        AZs:
          Fn::GetAtt:
          - VPC
          - Outputs.PublicAZs
        SubnetId:
          Fn::GetAtt:
          - VPC
          - Outputs.PublicSubnetId
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/1c9768def5544e41b383fd8cb75dff4d.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
  VPC:
    Properties:
      TemplateURL: https://s3.amazonaws.com/team1-cicd-pipeline-staging/621c0ebbf15d62d100e1cad918c3d426.template
      TimeoutInMinutes: '10'
    Type: AWS::CloudFormation::Stack
